channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=25.1.1
- pip:
  - mlflow==2.12.1
  - cffi==1.17.1
  - cloudpickle==3.1.1
  - lightgbm==4.6.0
  - matplotlib==3.8.4
  - numpy==1.26.4
  - packaging==24.2
  - pandas==2.2.2
  - psutil==5.9.8
  - pyarrow==15.0.2
  - pyyaml==6.0.2
  - scikit-learn==1.7.1
  - scipy==1.15.3
name: mlflow-env
